name: Build and Run Docker Container
on:
  push:
    branches:
    - main
  workflow_dispatch:  

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to ghcr
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PUBLISH_TOKEN }}

    - name: Build and Tag Docker Image
      run: |
        docker build -t ghcr.io/krisciu/FreeLlamas:${{ github.sha }} .
        docker push ghcr.io/krisciu/FreeLlamas:${{ github.sha }}